name: strict_config
description: Configuration parser with error checking and support for logging.
version: 1.0.0
homepage: https://github.com/hoylen/strict_config

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  logging: ^0.11.4
  yaml: ^2.2.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
