name: strict_config
description: Configuration parser with error checking, validation and logging config support.
version: 2.1.1
homepage: https://github.com/hoylen/strict_config

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  logging: ^1.0.0
  yaml: ^3.0.0

dev_dependencies:
  lints: ^2.1.1
  pana: ^0.21.37
  test: ^1.16.3
