name: strict_config
description: Configuration parser with error checking, validation and logging config support.
version: 2.0.0
homepage: https://github.com/hoylen/strict_config

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  logging: ^1.0.0
  yaml: ^3.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.3
